20200529

### 问题描述

今天在写一道递归题时，在递归函数外定义了一个变量，在函数体内对该变量进行了修改，但是程序报错如下：

```
UnboundLocalError: local variable 'prev' referenced before assignment
```



先来看看我的代码：

```
def isValidBST(root):
    prev = None
    
    def helper(root):
        if not root:
            return 
		
		# 左子树
        helper(root.left)
        
        if not prev:
            nonlocal prev 
            prev = root.val
        elif root.val > prev:
            prev = root.val
        else:
            return False
        # 右子树
        helper(root.right)
        
    helper(root)
    return True
```



我感觉奇怪，明明是在函数外面声明的prev变量，按理来说应该对于helper函数来说应该是一个global variable呀。

而且把prev换成数组的话，是可以在helper函数体里面直接append()的，也没报错呀。



### 原因分析

去google了一下，看到这篇回答：

> You defined n as a global variable here:
>
> ```py
> n = 1
> ```
>
> Then later redefined it in `n_inc` as a local variable
>
> ```py
> n = n + 2
> ```
>
> This means n is now a local variable and you cannot use it in conts_frac. 



似乎是因为在函数体内**对变量值进行了修改**：`prev=root.val `，其实是**创建了一个同名为prev的新变量**，导致该变量成为了一个local variable，因此下一次再进入到函数体时（递归），就会报错了。

而使用list不会报错的原因是：list仅仅是append，也就是只是对原数组进行修改而没有创建新的list，所以list可以一直作为全局的list使用。



### 解决方案

- nonlocal 关键字申明
-  renaming variable, 
- implementing a main function,
-  or adjusting your function parameters to use `n`



至于这道题，我的解决方案是：

未完待续



### 参考资料：

https://stackoverflow.com/questions/34072122/unboundlocalerror-when-i-am-trying-to-do-recursion-from-loop

https://stackoverflow.com/questions/8934772/assigning-to-variable-from-parent-function-local-variable-referenced-before-as